name: Check Release

on:
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        id: checking
        continue-on-error: true
        env:
            GH_TOKEN: ${{github.token}}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/tags/v11.0.5
     
      - name: Echoing
        run: echo ${{steps.checking.outcome}}
      
      - name: Check if exists
        run: |
          if [[ ${{steps.checking.outcome}} == 'failure' ]]; then
            echo "The version does not exists"
          elif [[ ${{steps.checking.outcome}} == 'success' ]]; then
            echo "The version exists."
            echo "::error::The version already exists"
          fi
          
          echo "Version exists"
