name: Create Release

on:
  workflow_call:
    inputs:
      owner:
        description: 'The personal owner or organization owner of the repository'
        required: true
        type: string
      repository_name:
        description: 'The repository name'
        required: true
        type: string
      tag_name:
        description: 'The tag that will recieve the commit for this release and the name of the release'
        required: true
        type: string
    secrets:
      access_token:
        description: 'The GitHub access token to authorizate the release creation command'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create-release
        run: |        
            CREATE_RELEASE=$(curl -L -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer ${{ secrets.access_token }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repository_name }}/releases \
                -d '{"tag_name":"${{ inputs.tag_name }}","target_commitish":"main","name":"${{ inputs.tag_name }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}')
            RELEASE_ID=$(echo "$CREATE_RELEASE" | jq -r '.id')
            echo "release_id=$RELEASE_ID" >> "$GITHUB_OUTPUT"
