name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
            curl -L -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/awesomel-es/slave-repository/releases \
                -d '{"tag_name":"v9.0.0","target_commitish":"main","name":"v9.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'

