name: Create Release and Upload Artifact

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
        ARTIFACT_NAME: test
        FILE_NAME: test.txt
        OWNER: awesomel-es
        REPO: slave-repository
        RELEASE_ID: 110330365
        TAG_NAME: v10.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        id: create-release
        run: |        
            CREATE_RELEASE=$(curl -L -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases \
                -d '{"tag_name":"${{ env.TAG_NAME }}","target_commitish":"main","name":"${{ env.TAG_NAME }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}')
            RELEASE_ID=$(echo "$CREATE_RELEASE" | jq -r '.id')
            echo "release_id=$RELEASE_ID" >> "$GITHUB_OUTPUT"
      - name: Upload Release Asset
        run: |
            UPLOAD_RELEASE_ASSET=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.API_GH_TK }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: application/octet-stream" \
                https://uploads.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases/${{ steps.create-release.outputs.release_id }}/assets?name=${{env.FILE_NAME}} \
                --data-binary "@${{env.FILENAME}}")