name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: create-release
        with:
          result-encoding: string
          github-token: ${{ secrets.API_GH_TK }}
          retries: 3
          script: |
            const release_created = await github.request('POST /repos/awesomel-es/slave-repository/releases', {
                owner: 'awesomel-es',
                repo: 'slave-repository',
                tag_name: 'v4.0.2',
                target_commitish: 'main',
                name: 'v4.0.2',
                body: 'Description of the release',
                draft: false,
                prerelease: false,
                generate_release_notes: false,
                headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                }
            })
            console.log(release_created.data)
            core.setOutput('release_id', release_created.data.id);

      - uses: actions/github-script@v6
        id: my-script
        with:
            result-encoding: string
            github-token: ${{ secrets.API_GH_TK }}
            retries: 3
            script: |
                console.log('Release ID: ${{ steps.create-release.outputs.release_id }}')
                const assetUploaded = await github.request('POST /repos/awesomel-es/slave-repository/releases/${{steps.create-release.outputs.release_id}}/assets{?name,label}', {
                    owner: 'awesomel-es',
                    repo: 'slave-repository',
                    name: 'test.txt',
                    label: 'test.txt',
                    data: '@test.txt',
                    headers: {
                        'X-GitHub-Api-Version': '2022-11-28'
                    }
                })