name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.API_GH_TK }}
    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --hostname HOSTNAME \
            /repos/$OWNER/$REPO/releases/$RELEASE_ID/assets?name=test.txt \
            -f '@test.txt'
        env:
            OWNER: awesomel-es
            REPO: slave-repository
            RELEASE_ID: 110316636