name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.API_GH_TK }}
        REPO: slave-repository
        OWNER: awesomel-es
    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases \
            -d '{
                "tag_name":"v6.0.0",
                "target_commitish":"master",
                "name":"v6.0.0",
                "body":"Description of the release",
                "draft":false,
                "prerelease":false,
                "generate_release_notes":false
                }'