name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: create-release
        with:
          result-encoding: string
          github-token: ${{ secrets.API_GH_TK }}
          retries: 3
          script: |
            const release_created = await github.request('POST /repos/awesomel-es/slave-repository/releases', {
                owner: 'awesomel-es',
                repo: 'slave-repository',
                tag_name: 'v4.1.10',
                target_commitish: 'main',
                name: 'v4.1.10',
                body: 'Description of the release',
                draft: false,
                prerelease: false,
                generate_release_notes: false,
                headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                }
            })
            console.log(release_created.data)
            core.setOutput('release_id', release_created.data.id);
            core.setOutput('upload_url', release_created.data.upload_url);
      - uses: actions/github-script@v6
        id: my-script
        with:
            result-encoding: string
            github-token: ${{ secrets.API_GH_TK }}
            retries: 3
            script: |
                console.log('Release ID: ${{ steps.create-release.outputs.release_id }}')
                const file_name = 'test.txt';
                const url = '${{steps.create-release.outputs.upload_url}}'.replace('https://uploads.github.com', '')
                console.log(url, ${{url}})
                await github.request('POST ${{url}}', {
                    owner: 'awesomel-es',
                    repo: 'slave-repository',
                    release_id: ${{ steps.create-release.outputs.release_id }},
                    data: `@${{file_name}}`,
                    headers: {
                        'X-GitHub-Api-Version': '2022-11-28'
                    }
                })
