name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: create-release
        with:
          result-encoding: string
          github-token: ${{ secrets.API_GH_TK }}
          retries: 3
          script: |
            const repo = 'slave-repository';
            const release_created = await github.request(`POST /repos/awesomel-es/${repo}/releases`, {
                owner: 'awesomel-es',
                repo: repo,
                tag_name: 'v4.2.0',
                target_commitish: 'main',
                name: 'v4.2.0',
                body: 'Description of the release',
                draft: false,
                prerelease: false,
                generate_release_notes: false,
                headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                }
            });
            console.log(release_created.data)
            core.setOutput('release_id', release_created.data.id);
            core.setOutput('upload_url', release_created.data.upload_url);

