name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: upload-asset
        with:
            result-encoding: string
            github-token: ${{ secrets.API_GH_TK }}
            retries: 3
            script: |
                const repo = 'slave-repository'
                const owner = 'awesomel-es'
                const release_id = '110316980'
                console.log(release_id)
                const file_name = 'test.txt'
                const upload_asset = await github.request('POST https://uploads.github.com/repos/awesomel-es/slave-repository/releases/110316980/assets{?name,label}', {
                    owner: owner,
                    repo: repo,
                    release_id: release_id,
                    data: '@${file_name}',
                    headers: {
                        'X-GitHub-Api-Version': '2022-11-28'
                    }
                })