name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.API_GH_TK }}
    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - run: gh release upload $OWNER/$REPO $RELEASE_ID --clobber test.txt

        env:
            OWNER: awesomel-es
            REPO: slave-repository
            RELEASE_ID: 110316636