name: Create Release 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          retries: 3
          script: |
            const octokit = new Octokit({
                auth: ${{ secrets.API_GH_TK }}
            })

            await octokit.request('POST /repos/{owner}/{repo}/releases', {
                owner: 'awesomel-es',
                repo: 'slave-repository',
                tag_name: 'v2.0.0',
                target_commitish: 'main',
                name: 'v2.0.0',
                body: 'Description of the release',
                draft: false,
                prerelease: false,
                generate_release_notes: false,
                headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                }
            })