name: Main Step by Step

on:
  workflow_dispatch:

env:
    upload_artifact_name: test
    upload_file_name: test.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Echoing data
        run: |
            echo '${{ github.event.repository.name }}'
            echo '${{ github.repository_owner }}'
            ls -la

      - name: Build
        run: echo 'Done'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: ${{ env.upload_artifact_name }}
            path: ${{ env.upload_file_name }} 

  create-release:
    needs: build
    uses: awesomel-es/slave-repository/.github/workflows/create_release.yml@main
    with:
        owner: ${{ github.repository_owner }}
        repository_name: ${{ github.event.repository.name }}
        tag_name: v11.0.3
    secrets:
        access_token: ${{ secrets.API_GH_TK }}
  
  upload-asset:
    needs: create-release
    uses: awesomel-es/slave-repository/.github/workflows/upload_asset_to_release.yml@main
    with:
        artifact_name: ${{ env.upload_artifact_name }}
        file_name: ${{ env.upload_file_name }}
        release_id: ${{ needs.create-release.outputs.release_id }}
        owner: ${{ github.repository_owner }}
        repository_name: ${{ github.event.repository.name }}
    secrets:
        access_token: ${{ secrets.API_GH_TK }}