name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Find Release Asset
        env:
          ASSET_NAME: test.txt
          REPO: slave-repository
          OWNER: awesomel-es
        id: find-asset
        run: |
          RELEASE_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
            "https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases/latest" | jq -r '.url')

          echo "Release URL: $RELEASE_URL"
          ASSET_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
            "$RELEASE_URL/assets" | jq -r ".[] | select(.name == \"${{ env.ASSET_NAME }}\") | .id")

          echo "Asset ID: $ASSET_ID"

          # Download the asset's binary content
          curl -LOJ -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases/assets/$ASSET_ID"

      - name: Echoing files
        run: ls -la