name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Release Asset
        id: find-asset
        run: |
          RELEASE_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
            "https://api.github.com/awesomel-es/slave-repository/releases/latest" | jq -r '.url')
      
          ASSET_NAME="Pictures.40a5emu33g7b1.jpg.webp"
          ASSET_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
            "$RELEASE_URL/assets" | jq -r ".[] | select(.name == \"$ASSET_NAME\") | .browser_download_url")
      
          echo "Asset URL: $ASSET_URL"
      