name: Release Asset to Artifact

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The artifact that should be downloaded in order to retrieve the asset'
        required: true
        type: string
      file_name:
        description: 'The asset file name'
        required: true
        type: string
      owner:
        description: 'The personal owner or organization owner of the repository'
        required: true
        type: string
      repository_name:
        description: 'The repository name'
        required: true
        type: string
    secrets:
      access_token:
        description: 'The GitHub access token to authorizate the release creation command'
        required: true

jobs:
  get-release-asset-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Find Release URL
        id: find-release-url
        run: |
          # Get the latest Release url
          RELEASE_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.access_token }}" \
            "https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repository_name }}/releases/latest" | jq -r '.url')

          echo "release_url=$RELEASE_URL" >> "$GITHUB_OUTPUT"

      - name: Find Asset ID
        id: find-asset-id
        run: |
          # Get the Asset ID by the filename
          ASSET_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.access_token }}" \
          "${{ steps.find-release-url.outputs.release_url }}/assets" | jq -r ".[] | select(.name == \"${{ inputs.file_name }}\") | .id")

          echo "asset_id=$ASSET_ID" >> "$GITHUB_OUTPUT"
        
      - name: Download Asset
        run: |
          # Download the asset's binary content
          curl -LOJ -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.access_token}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repository_name }}/releases/assets/${{ steps.find-asset-id.outputs.asset_id }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: ${{ inputs.artifact_name }}
            path: ${{ inputs.file_name }}