name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Creating release
        id: release-create
        run: |        
            const core = require('@actions/core');
            CREATE_RELEASE=$(curl -L -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer ${{ secrets.API_GH_TK }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases \
                -d '{"tag_name":"${{ env.TAG_NAME }}","target_commitish":"main","name":"${{ env.TAG_NAME }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}')
            RELEASE_URL=$(echo "$CREATE_RELEASE" | jq -r '.url')
            echo "Release URL: $RELEASE_URL"
            core.setOutput('outputKey', 'outputVal');
        env:
          TAG_NAME: v9.0.7
          REPO: slave-repository
          OWNER: awesomel-es
      
      - run: echo "url ${{ steps.release-create.outputKey }}"