name: UPLOAD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echoing files
        run: ls -la

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Creating release
        id: release-create
        run: |
            UPLOAD_RELEASE_ASSET=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.API_GH_TK }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: application/octet-stream" \
                https://uploads.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases/${{ env.RELEASE_ID }}/assets?name=${{ env.FILENAME }} \
                --data-binary "@${{env.FILENAME}}")
            echo "UPLOAD $UPLOAD_RELEASE_ASSET"

        env:
          REPO: slave-repository
          OWNER: awesomel-es
          RELEASE_ID: 110330365
          FILENAME: test.txt
